source 'https://rubygems.org'

gem 'jekyll'
gem 'therubyracer' # required by jekyll
group :jekyll_plugins do
    gem "directory-structure-generator", :path => "chime/directory-structure-generator"
end
